[build]
  command = "npm --prefix team_nexa_logistics/backend install"
  publish = "team_nexa_logistics/frontend"
  functions = "team_nexa_logistics/backend"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
