[build]
  base = "team_nexa_logistics"
  command = "cd backend && npm install"
  publish = "frontend"
  functions = "backend"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200
